[package]
edition = "2021"
name = "auth-app-rs"
version = "0.1.0"
build = "build.rs"
[dependencies]
actix-service = "2.0.2"
actix-web = "4.0.1"
anyhow = "1.0.56"
clap = { version = "3.1.9", features = ["derive", "env"] }
dotenv = "0.15.0"
prometheus = "0.13.0"
rust-argon2 = "1.0.0"
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.79"
shadow-rs = "0.11.0"
sqlx = { version = "0.5.13", features = ["runtime-actix-rustls", "postgres"]}

[build-dependencies]
shadow-rs = "0.11.0"

[dev-dependencies]
testcontainers = { version ="0.13.0"}

