[package]
edition = "2021"
name = "auth-app-rs"
version = "0.1.0"
build = "build.rs"
[dependencies]
actix-web = "4"
clap = "3.1.8"
config = { version = "0.13.0", features = ["json", "ini", "toml"] }
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.79"
shadow-rs = "0.11.0"
sqlx = { version = "0.5.11", features = ["runtime-actix-rustls", "postgres"]}

[build-dependencies]
shadow-rs = "0.11.0"
[dev-dependencies]
testcontainers = { version ="0.13.0"}

