-- Add up migration script here
ALTER TABLE instances ADD COLUMN trial_expiry TIMESTAMP WITH TIME ZONE;
ALTER TABLE instances ADD COLUMN trial_start TIMESTAMP WITH TIME ZONE;
ALTER TABLE instances ADD COLUMN instance_state TEXT NOT NULL DEFAULT 'UNASSIGNED';
ALTER TABLE instances ADD COLUMN trial_extended INTEGER NOT NULL DEFAULT 0;
ALTER TABLE instances ADD COLUMN billing_center TEXT NOT NULL DEFAULT 'EU';
ALTER TABLE instances ADD COLUMN seats INTEGER NOT NULL DEFAULT 5;
